#!/bin/bash

#SBATCH --job-name=symm_check
#SBATCH --ntasks=1 # Specify the number of nodes you want to run on
##SBATCH --mail-type=FAIL # Receive an email if your job fails

echo "Time: `date`" > jobnumber

echo $SLURM_NTASKS > nodes.info
srun hostname >> nodes.info
echo $USER >> nodes.info
pwd >> nodes.info
/sharedscratch/nn320/softwarewales/GMIN/builds/gfortran/A12GMIN >> output
echo Finished at `date` >> jobnumber
