#!/bin/bash

#SBATCH --job-name=monomerBHtest
#SBATCH --partition=TEST
#SBATCH -n1 -N1
##SBATCH --mail-type=FAIL # Receive an email if your job fails

echo "Time: `date`" > jobnumber

echo $SLURM_NTASKS > nodes.info
srun hostname >> nodes.info
echo $USER >> nodes.info
pwd >> nodes.info

module purge # unload all modules from user's environment.
module load gcc/7.5.0

/sharedscratch/nn320/softwarewales/GMIN/builds/gfortran/A12GMIN > output

echo Finished at `date` >> jobnumber
