#!/bin/bash

#SBATCH -p TEST
#SBATCH --job-name=addminxyz
#SBATCH -n40 -N1
##SBATCH --mail-type=FAIL # Receive an email if your job fails
##SBATCH --time=04:00:00

echo "Time: `date`" > jobnumber

echo $SLURM_NTASKS > nodes.info
srun hostname >> nodes.info
echo $USER >> nodes.info
pwd >> nodes.info

/sharedscratch/nn320/softwarewales/PATHSAMPLE/builds/gfortran/PATHSAMPLE > output
echo Finished at `date` >> jobnumber

